http:
  routers:
    api:
      rule: 'Host(`traefik.mvbureev.ru`)'
      entrypoints:
        - websecure
      middlewares:
        - simpleAuth
      service: api@internal
      tls:
        certResolver: lets-encrypt
