entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

http:
  routers:
    http-catchall:
      rule: hostregexp(`{host:.+}`)
      entrypoints: 
      - http
      middlewares: 
      - redirect-to-https
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false

api:
  dashboard: true

certificatesResolvers:
  lets-encrypt:
    acme:
      email: mvbureev@gmail.com
      storage: acme.json
      caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      tlsChallenge: {}
      httpChallenge:
        entryPoint: http

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
  file:
    filename: traefik_dynamic.toml
